### ISSUE TITLE
How can one test the prepend() method ?

### ISSUE THREAD

**Issue by greg0ire** [matthiasnoback/SymfonyDependencyInjectionTest#38]
I made [a P.R.](https://github.com/sonata-project/SonataCoreBundle/pull/108/files) with a modification to the extension so that it uses the `prepend()` method of the extension to test the presence of a related configuration node for another bundle (`SonataAdminBundle`). Is it possible to test that with your library ?

**Comment by zebba** [comment]
I tested prepend() using this approach: https://github.com/alameda-red/DoctrineExtensionsBundle/blob/master/Tests/DependencyInjection/AlamedaDoctrineExtensionsExtensionTest.php

**Comment by matthiasnoback** [comment]
Sorry about the late reply. @zebba Looks good to me!
The example already looks quite good to me. Only problem is you have to keep repeating knowledge about `kernel.bundles`, registering extensions and fetching extension configs. So maybe this can be turned into something more generic. Do you have an idea for that already?

**Comment by matthiasnoback** [comment]
Closing this since there's no action required (if I understand correctly ;)).
