### ISSUE TITLE
[RFC] make ContainerBuilderHasAliasConstraint case-insensitive

### ISSUE THREAD

**Issue by xabbuh** [matthiasnoback/SymfonyDependencyInjectionTest#39]
When writing tests for a legacy application, I discovered that the checks performed in the `ContainerBuilderHasAliasConstraint` are not case-insensitive.

For example, take the following service definition and alias:

```yaml
services:
   fooBar:
     class: \Foobar
   foo:
     alias: fooBar
```

Notice the capitalised *B* in the service id for the `fooBar` service definition. However, when using the `assertContainerBuilderHasAlias()`, you will have to lowercase the service id. The reason is that the Symfony DependencyInjection component lowercases all service ids and aliases.

I suggest to reflect this behaviour in the `ContainerBuilderHasAliasConstraint` and would be happy to open a pull request for this. Though I first wanted to ask for your opinion on this.

@matthiasnoback What do you think?

**Comment by matthiasnoback** [comment]
Interesting!
Yes it makes sense to fix that. If you find some time for a PR, that's much
appreciated. Even though I think that the ContainerBuilder should be fixed
as well ;)
Op 17 apr. 2015 14:24 schreef "Christian Flothmann" <
notifications@github.com>:

**Comment by xabbuh** [comment]
See #40 for the fix.

@matthiasnoback I don't think that anything in the `ContainerBuilder` needs to be fixed. Can you explain what you mean?

**Comment by matthiasnoback** [comment]
Of course, you're right. I misunderstood the problem.
