### ISSUE TITLE
Can't install with config-test 1.0

### ISSUE THREAD

**Issue by rdohms** [matthiasnoback/SymfonyDependencyInjectionTest#41]
Because of the restriction to `0.*` of the config tester, this cannot be installed along side of it when using `~1.0` for the config package.

**Comment by matthiasnoback** [comment]
Thanks @rdohms for reporting and thanks @xabbuh for fixing this!

**Comment by rdohms** [comment]
Thanks, but can you tag a release?

**Comment by matthiasnoback** [comment]
Done!

**Comment by rdohms** [comment]
:+1: thanks!
