### ISSUE TITLE
Bundle::build() test?

### ISSUE THREAD

**Issue by Soullivaneuh** [matthiasnoback/SymfonyDependencyInjectionTest#45]
Hi and thanks for this library, this gave me lot of time to make tests.

In your documentation, it's explain how to test `Extenstion` and `CompilerPass`, but what about the `Bundle` class itself?

For example, I would like to test the build method of this `Bundle` class: 
https://github.com/Soullivaneuh/SLLHIsoCodesValidatorBundle/blob/master/src/SLLHIsoCodesValidatorBundle.php

Is that possible with your library? How?

Thanks.

**Comment by matthiasnoback** [comment]
In this case you can just mock the ContainerBuilder instance and call the
build method :)

Otherwise you should create a full functional test for your bundle.
Op 23 apr. 2015 14:55 schreef "Sullivan SENECHAL" <notifications@github.com

**Comment by Soullivaneuh** [comment]
Yeah just figure out how to do.

Is seems to be correct for you? https://github.com/Soullivaneuh/SLLHIsoCodesValidatorBundle/blob/master/tests/SLLHIsoCodesValidatorBundleTest.php

Thanks for your help. :+1:

**Comment by matthiasnoback** [comment]
In my opinion this doesn't really add that much quality to the bundle test
suite. You'd be better of with a test that creates a kernel, registers a
bundle, boots the kernel and verifies that everything works.
Op 23 apr. 2015 16:48 schreef "Sullivan SENECHAL" <notifications@github.com

**Comment by Soullivaneuh** [comment]
Hmm don't really understand.

My [SLLHIsoCodesValidatorBundle](https://github.com/Soullivaneuh/SLLHIsoCodesValidatorBundle/blob/master/src/SLLHIsoCodesValidatorBundle.php) class just add a compiler to the given container.

I just have to test what the class do, isn't it?

I should better improve test for [TranslationPass.php](https://github.com/Soullivaneuh/SLLHIsoCodesValidatorBundle/blob/master/src/DependencyInjection/Compiler/TranslationPass.php) class with resources presence check.

Thanks for your advice anyway. :-)

**Comment by matthiasnoback** [comment]
Well, you could also mock the `ContainerBuilder`, call `build()` and see if the call to `addCompilerPass()` was made. However, this isn't a very interesting test.
Maybe take a look at this: https://github.com/SimpleBus/AsynchronousBundle/blob/master/tests/Functional/SimpleBusAsynchronousBundleTest.php It tests a bundle by testing if, when added to a kernel (https://github.com/SimpleBus/AsynchronousBundle/blob/master/tests/Functional/TestKernel.php) it integrates nicely, collects services by tag, etc.

**Comment by Soullivaneuh** [comment]
> Well, you could also mock the ContainerBuilder, call build() and see if the call to addCompilerPass() was made.

Also. But the test assertions goal will be the same, isn't it?

Thanks for examples, I'll take a look. :+1:

**Comment by matthiasnoback** [comment]
Well, it's not really the same, since your test is now coupled to the implementation of `ContainerBuilder` (since you expect 2 compiler passes, the second of which is your pass, which is too much knowledge about the internals of that class).

**Comment by matthiasnoback** [comment]
Closing this since there's no action required (right?).
