### ISSUE TITLE
Deprecated method

### ISSUE THREAD

**Issue by theofidry** [matthiasnoback/SymfonyDependencyInjectionTest#46]
Would be great to take care of this:

```
Symfony\Component\DependencyInjection\Definition::setFactoryMethod method is deprecated since version 2.6 and will be removed in 3.0. Use Definition::setFactory() instead
```

Thanks again for your library!

**Comment by xabbuh** [comment]
@theofidry The deprecation is not trigger by the testing library, but is triggered by Symfony itself.

**Comment by theofidry** [comment]
Oh yes my bad. Sorry for the inconvenience.

**Comment by matthiasnoback** [comment]
No problem, thanks @xabbuh for clarifying.
