### ISSUE TITLE
PHPUnit 5 compatibility

### ISSUE THREAD

**Issue by xabbuh** [matthiasnoback/SymfonyDependencyInjectionTest#54]
There are currently some issues regarding compatibility with PHPUnit 5 which is quite important as PHPUnit 4 is not fully compatible with PHP 7.

@matthiasnoback Just to keep track of this issue. :)

**Comment by matthiasnoback** [comment]
Thanks for adding it here - we'll see whoever will get to fixing it first :)

**Comment by matthiasnoback** [comment]
This will be fixed with the upcoming release :)
