### ISSUE TITLE
Add support for testing if a extension still allows the container to be dumped

### ISSUE THREAD

**Issue by boekkooi** [matthiasnoback/SymfonyDependencyInjectionTest#56]
Hi, 

So a while back I ran into a problem being that the extension that I was testing created a container instance that couldn't be dumped (but passed all tests).

To fix this I added the following assert to my TestCase:
```PHP
use Symfony\Component\DependencyInjection\Dumper;

class TestCase {
....
    /**
     * Assert that the current container can be dumped.
     */
    private function assertContainerCanBeDumped()
    {
        $dumperCalls = array(
            Dumper\XmlDumper::class,
            Dumper\PhpDumper::class,
            Dumper\GraphvizDumper::class,
            Dumper\YamlDumper::class,
        );
        foreach ($dumperCalls as $dumperClass) {
            /** @var Dumper\Dumper $dumper */
            $dumper = new $dumperClass($this->container);
            $this->assertInstanceOf(Dumper\Dumper::class, $dumper);
            $dumper->dump();
        }
    }
....
}
```

Would this be worth creating a PR?

**Comment by xabbuh** [comment]
@boekkooi Can you explain how your container looked like when you were not able to dump it?

**Comment by boekkooi** [comment]
A simple way to create a undumpable container is to set a instance as a service argument. 
For example:
```PHP
class MyExtension extends Extension
{
    /**
     * @inheritdoc
     */
    public function load(array $config, ContainerBuilder $container)
    {
....
        $def = new Definition('stdClass');
        $def->addArgument(new \stdClass());
        $container->setDefinition('test', $def);
....
    }
}

```

This has happened for example here https://github.com/boekkooi/tactician-amqp-bundle/commit/af605087c80a1f857d2d2a967a00230311439f88

**Comment by xabbuh** [comment]
I see, that's something that would indeed be caught by such a test. However, such a test would also fail under other circumnstances where you would not expect it or were it doesn't matter for your application. Ffor example, the YAML dumper does not support anonymous services (which is perfectly fine when dumping to PHP or XML).

**Comment by boekkooi** [comment]
Good point still maybe reworking the assert to accept the type of dumper would be a good idea then again nobody is forced to use the assert :smile: I was just wondering if creating a PR for this would be a good idea.

So make it something like `protected function assertContainerCanBeDumpedAs($type = 'php')`?

**Comment by matthiasnoback** [comment]
@boekkooi Thanks for bringing this up. However, as can be seen here: https://github.com/matthiasnoback/SymfonyDependencyInjectionTest/blob/master/PhpUnit/AbstractContainerBuilderTestCase.php#L18 the test scenario isn't a very realistic one so I doubt how much trust in an extension class this new assertion will bring us. If you want to be sure that a container can be dumped, you should create a test kernel and register your bundle as well as other bundles that are needed for successful execution. While booting that test kernel it will also be dumped to afaik PHP and XML (maybe in a temporary directory, but at least you will catch any exceptions caused by dumping it).

**Comment by boekkooi** [comment]
@matthiasnoback Thanks for the response. It was just a idea and you are correct a kernel would be the best solution. Thank you for taking the time!

**Comment by matthiasnoback** [comment]
@boekkooi Thanks for an interesting discussion! See you next time :)
