### ISSUE TITLE
Proper access of the kernel.bundles parameter

### ISSUE THREAD

**Issue by Soullivaneuh** [matthiasnoback/SymfonyDependencyInjectionTest#60]
I am trying to integrate your package under SonataAdminBundle: https://github.com/sonata-project/SonataAdminBundle/pull/3932

Our `SonataAdminExtension` currently need the `kernel.bundles` parameter: https://github.com/sonata-project/SonataAdminBundle/blob/3.2.0/DependencyInjection/SonataAdminExtension.php#L37

But we got this error:

``` bash
1) Sonata\AdminBundle\Tests\SonataAdminExtensionTest::testLoad
Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "kernel.bundles".

/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/vendor/symfony/dependency-injection/ParameterBag/ParameterBag.php:84
/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/vendor/symfony/dependency-injection/Container.php:127
/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/DependencyInjection/SonataAdminExtension.php:220
/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:36
/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/vendor/symfony/dependency-injection/Compiler/Compiler.php:104
/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/vendor/symfony/dependency-injection/ContainerBuilder.php:545
/home/sullivan/projects/fork/sonata-project/SonataAdminBundle/Tests/DependencyInjection/SonataAdminExtensionTest.php:24
```

What is the best way to get/simulate this parameter this your package? Can this be possible?

**Comment by matthiasnoback** [comment]
Well, you can override `setUp()` in your test class and call `parent::setUp()`, then set the parameter on the container (`$this->container->setParameter(...)`).

**Comment by Soullivaneuh** [comment]
This is the dirty way (IMO) I was thinking. :-)

No way to set up properly the bundles like an `AppKernel` file would do?

Or maybe this is no relevant here?

**Comment by matthiasnoback** [comment]
I must say that I changed my mind about this type of testing tools. I think that testing the extension in isolation doesn't make a lot of sense since it doesn't tell you if the remaining parts of the Symfony bundle system work correctly with your bundle. So nowadays I like to do these kinds of application tests: https://github.com/SimpleBus/SymfonyBridge/blob/master/tests/Functional/SmokeTest.php

**Comment by matthiasnoback** [comment]
Closing this as there's nothing to do.
