### ISSUE TITLE
PHPUnit 6 compatibility

### ISSUE THREAD

**Issue by garak** [matthiasnoback/SymfonyDependencyInjectionTest#66]
If you bump requirement for phpunit to `^5.7|^6.0`, you can use `PHPUnit\Framework\TestCase` instead of `PHPUnit_Framework_TestCase` (in 5.7 there is a forward-compatible layer).
Of course, this means dropping support for phpunit 4 (that is out of support, by the way)

**Comment by greg0ire** [comment]
I think this should be done in a major release, because `phpunit/phpunit` is in the `require-dev` section.

**Comment by matthiasnoback** [comment]
Fixed this in release v2.0.0.
