### ISSUE TITLE
[FEATURE]: assertContainerBuilderHasServiceDefinitionWithMethodCall - unable to test implementation of chain of responsibility 

### ISSUE THREAD

**Issue by TheCelavi** [matthiasnoback/SymfonyDependencyInjectionTest#69]
Considering that there is a service of type of "Registry", which gets injected with services of types of "Handler" via method call "addHendler" -> if order of injection of each individual handler via method call is significant, we are not able to test it.

Proposal: extend method signature of assertContainerBuilderHasServiceDefinitionWithMethodCall() to:

    protected function assertContainerBuilderHasServiceDefinitionWithMethodCall(
        $serviceId,
        $method,
        array $arguments = array(),
        $index = null // Zero-based order of invocation of method call
    )

This implementation will be BC compatible, if $index is provided, assert should check if method call has appropriate order in collection of registered method calls.

Application is useful, of course, when testing implementation of chain of responsibility pattern and/or visitor pattern where order of injection is prioritized.

I am willing to submit a patch, if you agree that this is a valid request for improvement.

**Comment by TheCelavi** [comment]
Sorry - missing info: Injection of "Handler" services via method call is done via tagged services, where priority is provided. Compiler pass would sort services according to priority and add a method calls to the definition of "Registry".

For now, we are not able to test if this sorting is properly executed.

**Comment by matthiasnoback** [comment]
Hi, I'm sorry, I've not been working on or with this library for some time now. I am definitely willing to merge your proposal, in particular as I think it would make sense for more people. Please provide a PR, with tests and updated documentation :)

**Comment by TheCelavi** [comment]
What? Why? What is wrong with this library? Are you planing to depreciate it? Why? Is there better alternative?

If there is no better alternative, and you do depreciate library, you know what comes next: [https://cdn.meme.am/cache/instances/folder517/25205517.jpg](https://cdn.meme.am/cache/instances/folder517/25205517.jpg)

😄  😄  😄 

Ok, I will write a patch and make a PR.

**Comment by matthiasnoback** [comment]
Mainly: I haven't done any big Symfony projects for almost 2 years ;)
I won't deprecate it, as it has its use cases, but I do believe that I would personally shift my focus while testing to testing the bundle as a whole, or in a fully functional setup. I intend to blog about this some day, but have been quite busy with some other technical content lately.
Anyway, thanks and looking forward to seeing your PR.

**Comment by TheCelavi** [comment]
Would you please bump version to 2.0.1 ? 

I can not fetch this feature without using "dev-master"....

**Comment by matthiasnoback** [comment]
I did actually: v2.1.0. Although it's not an official release, it is an official tag :)

**Comment by TheCelavi** [comment]
Hm... there is something wrong on packagist then... 

Version is missing, see: https://packagist.org/packages/matthiasnoback/symfony-dependency-injection-test - there is no 2.1.0? Should I raise issue there?

**Comment by matthiasnoback** [comment]
Okay, I clicked "Update" on packagist.org, don't know what could've gone wrong, but the new version is there now :)

**Comment by TheCelavi** [comment]
Thanks!
