### ISSUE TITLE
error after installing version 2.0

### ISSUE THREAD

**Issue by OskarStark** [matthiasnoback/SymfonyDependencyInjectionTest#70]
![screenshot 2017-03-07 12 26 31](https://cloud.githubusercontent.com/assets/995707/23654517/507982fa-0331-11e7-8bbc-76f96c764844.png)

my tests are failing, I am wondering, why I can install version >=2.0, if i have PHPUnit 5.7.15 installed:
```
oskar.stark:/Volumes/development/workspaces/dashy (show-navi)$ composer show | grep phpunit/phpunit
phpunit/phpunit                                  5.7.15  The PHP Unit Testing framework.
```

```
oskar.stark:/Volumes/development/workspaces/dashy (show-navi)$ composer show | grep matthias
matthiasnoback/symfony-config-test               v3.0.1  Library for testing user classes related to the Symfony Config Component
matthiasnoback/symfony-dependency-injection-test v2.0.0  Library for testing user classes related to the Symfony Dependency Injection Component
```

IMO >=2.0 should have PHPUnit <=6.0 in the conflict section

**Comment by matthiasnoback** [comment]
I don't know how this is possible, since `matthiasnoback/symfony-dependency-injection-test v2.0.0` requires `phpunit/phpunit: ^6.0`...

**Comment by matthiasnoback** [comment]
Ah, I get it now. It's because phpunit is in the `require-dev` section of `symfony-dependency-injection-test`. That's because people using a separate .phar containing PHPUnit. See also: https://github.com/matthiasnoback/SymfonyDependencyInjectionTest/pull/68 I can't fix this, you just need to take care of the dep on 6.0 yourself.

**Comment by OskarStark** [comment]
good to know, thank you 👍

**Comment by matthiasnoback** [comment]
Thanks for reporting, and thanks for using this lib. I'll see if I can fix it by adding a warning about incorrect PHPUnit version usage :)
