### ISSUE TITLE
Show a warning when users don't run the correct PHPUnit version

### ISSUE THREAD

**Issue by matthiasnoback** [matthiasnoback/SymfonyDependencyInjectionTest#71]
See #70. Since we can't enforce a specific PHPUnit version using standard Composer techniques (e.g. in the `require` section), we need to warn the users about incompatible usage in another way.

**Comment by xabbuh** [comment]
One solution that could work might be to check for a class that was not present before PHPUnit 6 inside the `setUp()` method of the base test case class and skip the test otherwise.

**Comment by OskarStark** [comment]
@xabbuh that sounds good, but why not require it directly and IF someone like to use a .phar or a global installed version, it should work too, shouldn't it?

**Comment by lucasvanlierop** [comment]
I guess this this error has to do with this?

```php
PHPUnit 5.7.12 by Sebastian Bergmann and contributors.

PHP Fatal error:  Class 'PHPUnit\Framework\Constraint\Constraint' not found in /var/www/html/vendor/matthiasnoback/symfony-dependency-injection-test/PhpUnit/ContainerHasParameterConstraint.php on line 9
```

**Comment by matthiasnoback** [comment]
@lucasvanlierop It most likely does ;)

**Comment by lucasvanlierop** [comment]
:-) Which version do you recommend?

**Comment by matthiasnoback** [comment]
@lucasvanlierop You could either use PHPUnit ^6.0 or switch to a previous major version of this library, e.g. 1.1.0.

**Comment by lucasvanlierop** [comment]
Just did the latter thanks for confirming! Btw thanks for still maintaining this package! Used it a lot at Ibuildings and now I'm using it again for my new project ;-)

**Comment by matthiasnoback** [comment]
Cool, happy to hear that!

**Comment by matthiasnoback** [comment]
I've been thinking about this, but I can't come up with a good point to verify that the PHPUnit version used to run tests is the right one. The problem here is: I'd love to add this check to a `setUp()` method of some sorts, but the test runner crashes before it reaches this method, since it can't find the `TestCase` and related classes.
Anybody got another suggestion for this?

**Comment by lucasvanlierop** [comment]
It would be nice if composer could check if a class is present (autoloadable) on install the same way it can check the presence of a php extension

**Comment by matthiasnoback** [comment]
Closing this as I don't think there will be a solution. I'm sure with this item in the issue archive people will quickly figure out what's wrong when they encounter this situation :)
